Update options.md
yihui/yihui.org pull request #68
Opened 2019-05-21 02:06 UTC by jienagu

I edited from the beginning to Text Results `collapse`. I will work on the rest later.

2019-05-21 02:31 UTC, yihui reviewed
Great! Do you want me to review the PR now, or wait until you are done with this page?

2019-05-21 02:45 UTC, jienagu commented
How about review it from now so we don't have a backlog.

2019-05-21 03:19 UTC, yihui requested changes
Good start! One major problem of the **knitr** documentation site is that it was created with Rnw/LaTeX documents in mind in the beginning. I'd like to mention Rnw less frequently, and use R Markdown whenever possible. That said, you don't have to do this at the moment. We can leave it to the next step after this PR is merged.

2019-05-21 03:19 UTC, yihui commented on content/knitr/options.md
> +to be unique, i.e. no two chunks should share the same label. This is especially
It is no longer necessary to mention Sweave here: knitr was created to replace Sweave, and I guess it has done its job long time ago :)

2019-05-21 03:19 UTC, yihui commented on content/knitr/options.md
> +Take Rnw files as an example, usually we write chunk options in the form
The example below is not Rnw, but Rmd.

```suggestion
Take Rmd files as an example. Usually we write chunk options in the form
```

2019-05-21 03:19 UTC, yihui commented on content/knitr/options.md
> +And `opts_chunk$set()` can change the default global options of a document
I feel `in` is more appropriate here (or `inside`).

2019-05-21 03:19 UTC, yihui commented on content/knitr/options.md
> +1. Chunk options must be written in one line and no line breaks are allowed
I prefer short sentences.

```suggestion
1. Chunk options must be written on one line. No line breaks are allowed
```

2019-05-21 03:19 UTC, yihui commented on content/knitr/options.md
> +  replaced with `_` automatically.
Actually this is true only for Rnw documents, so I'd rather not mention the substitution at all.

2019-05-21 03:19 UTC, yihui commented on content/knitr/options.md
> +  - In theory, the chunk label should be quoted as well. But, for the sake of
```suggestion
  - In theory, the chunk label should be quoted as well. However, for the sake of
```

2019-05-21 03:19 UTC, yihui commented on content/knitr/options.md
> +    carefully because the syntax is different.
Let's just get rid of this bullet about Sweave.

2020-07-01 21:22 UTC, yihui approved these changes
I just finished the rest of work by myself. Thanks again!

2020-07-01 21:23 UTC, merged